# public-docker-compose.yml
# - only expose nginx port 8000

version: '3.9'
services:

  database:
    # default port 5432
    image: postgres:14
    container_name: portal-database
    networks:
      - portal-network
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
#    volumes:
#      - ${HOST_DB_DATA}:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    # default port 8000
    image: nginx:1
    container_name: portal-nginx
    networks:
      - portal-network
    ports:
      - "8000:80"
#      - "8080:80"
#      - "8443:443"
    volumes:
      - ./:/code
      - ./portal/static:/code/portal/static
      - ./portal/media:/code/portal/media
      - ${NGINX_DEFAULT_CONF}:/etc/nginx/conf.d/default.conf
#      - ${NGINX_SSL_CERTS_DIR}:/etc/ssl:ro
    restart: unless-stopped

  django:
    # default port 8000
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: portal-django
    networks:
      - portal-network
#    ports:
#      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./:/code
      - ./portal/static:/code/portal/static
      - ./portal/media:/code/portal/media
    environment:
      - UWSGI_UID=${UWSGI_UID}
      - UWSGI_GID=${UWSGI_GID}
    restart: unless-stopped

networks:
  portal-network:
    name: portal-network
    driver: bridge